import type { NextPage } from "next";
import Head from "next/head";
import { api } from "@acme/api/src/client";
import type { inferProcedureOutput } from "@trpc/server";
import type { AppRouter } from "@acme/api";
import SignInOutButton from "../utils/SignInOutButton";
import { ProtectedPageLink } from "@acme/app";

const PostCard: React.FC<{
  post: inferProcedureOutput<AppRouter["post"]["all"]>[number];
}> = ({ post }) => {
  return (
    <div className="max-w-2xl rounded-lg border-2 border-gray-500 p-4 transition-all hover:scale-[101%]">
      <h2 className="text-2xl font-bold text-[hsl(280,100%,70%)]">
        {post.title}
      </h2>
      <p>{post.content}</p>
    </div>
  );
};

const Home: NextPage = () => {
  const postQuery = api.post.all.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex h-screen flex-col items-center bg-gradient-to-b from-[#2e026d] to-[#15162c] text-white">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-8">
          <h1 className="text-5xl font-extrabold tracking-tight sm:text-[5rem]">
            Create <span className="text-[hsl(280,100%,70%)]">T3</span> Turbo
          </h1>
          <ProtectedPageLink />
          <AuthShowcase />

          <div className="flex h-[60vh] justify-center overflow-y-scroll px-4 text-2xl">
            {postQuery.data ? (
              <div className="flex flex-col gap-4">
                {postQuery.data?.map((p) => {
                  return <PostCard key={p.id} post={p} />;
                })}
              </div>
            ) : (
              <p>Loading..</p>
            )}
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: clerkuser } = api.auth.getSession.useQuery();

  const { data: secretMessage } = api.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: !!clerkuser }, // only run if clerkuser is defined
  );

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      {clerkuser && (
        <p className="text-center text-2xl text-white">
          {clerkuser && <span>Logged in as {JSON.stringify(clerkuser)}</span>}
          {secretMessage && <span> - {secretMessage}</span>}
        </p>
      )}
      <SignInOutButton />
    </div>
  );
};
